name: Python Lab

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Specify Python version to use'
        required: true
        default: '3.9'

jobs:
  setup-and-run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ github.event.inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Display Python version
        run: python --version